// svelte/src/routes/work/+page.svelte
<script lang="ts">
	import * as resume from '$lib/assets/resume.json';
	import Title from '$lib/components/Title.svelte';
	import Content from '$lib/components/Content.svelte';
</script>

<Content>
	<span slot="header">Work Experience</span>

	<ul slot="content">
		{#each resume.work as experience}
			<li>
				<Title level={2}>{experience.position}</Title>
				<Title level={3}>
					<span>{experience.name}</span>
					<span class="text-accent">
						{experience.startDate} - {experience.endDate ?? 'Present'}
					</span>
				</Title>
				<ul class="mb-6 list-disc pl-4">
					{#each experience.highlights as highlight}
						<li>
							{highlight}
						</li>
					{/each}
				</ul>
			</li>
		{/each}
	</ul>
</Content>

// angular/src/app/pages/work/work.component.ts
import { ChangeDetectionStrategy, Component, HostBinding } from "@angular/core";
import { CommonModule } from '@angular/common';
import * as resumeJSON from '../../../assets/resume.json';
import { ContentComponent } from "../../components/content.component";
import { TitleDirective } from "../../components/title.directive";
const resume = resumeJSON;

@Component({
  selector: 'app-work',
  standalone: true,
  imports: [CommonModule, ContentComponent, TitleDirective],
  template: `
    <app-content>
      <span header>Work Experience</span>
      <ul content>
        <li *ngFor="let experience of resume.work">
          <h2 appTitle [level]="2">{{ experience.position }}</h2>
          <h3 appTitle [level]="3">
            <span>{{ experience.name }}</span>
            <span class="text-accent">
            {{ experience.startDate }} - {{experience.endDate ?? 'Present'}}
            </span>
          </h3>
          <ul class="mb-6 list-disc pl-4">
            <li *ngFor="let highlight of experience.highlights">
              {{ highlight }}
            </li>

          </ul>
        </li>
      </ul>
    </app-content>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class WorkComponent {
  resume = resume;
}
